dist: xenial
sudo: required
language: generic
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::6}
services:
- docker
script:
- docker build -t wukong-provider .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker tag wukong-provider gyrosworkshop/wukong-provider:${COMMIT}
- docker push gyrosworkshop/wukong-provider:${COMMIT}
