language: node_js
node_js:
  - "9"
services:
  - redis-server
script:
  - npm install
  - npm run lint
  - npm run build
  # - npm run test
env:
  global:
    - secure: "Uq2FLhRv888D2PtCdFgLWA2FCos+i+BAhxluMYZV3QOjh0DqmXpDy2dJdlIQVrK9aTrF0eC36gdL8fc6eFV5S1QzSNtMIiqGdw3MM6u6EDcPX8wOHUyJTNhWzUd0ef6ySwpYUa4W/VmIXWlDEybfkxJACDfIEc1shuH/NPEAK+UZGYyCySM9R06cS/jIQMIIehAkqXDlLFFUubaUkqnSCOcB3NOUybHPE5lkdhjkwna9vEfvQjmueTzV+hmUTHhmcVDgpteWFZQZ6eBAea6hrhkHaggVdMFtWf6axvzNwomYIkpi9bwLmEFMSLu80UjM9em5y6DDlDOgusPswPDEnd3I++7rPEGDkREsUoWDB4LBJDYKwlcUQwHDFiHAZZc1gMbPg3M0nBlehJgi1cb5DWFbPYCy072m6IUX2CpxRtzIecyNfCTsKKtJ1Rlp3mdLj1MO4Qe5qaL0PYPCStw1n2msXr+YfXOoMlJo0w0DTxWTJbD4ZPyCMeS+G84xm1TnTVDfOy0IJss+3GZA6csEYK2d5WkTGC61Aeew1IU8krq+g39lX7U5rVFdHUFljPpf/M56I34+sxu3+HqK9Rz6yBJVi8gqEVEVgrj6Gp2zjIM3NPBrs33cqo9M/LQKsyeaH6ZW7eI9iEW6JRLEk9vZ1QPujEQAzNQnbJq8yB2aLbY="
    - secure: "iCutFkPzWkRU2CyGtBOyOEKz1Ze7Gm2u6kKqBui4AAjTiT5eUVDpc465sg+sKK/x6R7XogjaKj8i9ojLql3xjIwsgJYMV7q2Fr3/rDlWLwO58bCZaiicQ67QdOOlbTYjB3FCPPh4pcxw0ftMT6Wg8pfUm4qfHY0cFzMxAaikcJEXuYZ18e6f84x+2UpgmSBeWszZLnc7hRDtf8yEzhh4AWI8Q4IloOo3XqSuQgOeyHqBNJB3+eIdRbJwUvhbVLXJFAUYIdKireyIONrnAwFVXlC3f2qQGlAAK6oHTjiOAa/B+roLQ2XhGpnOSpyBKqEbpNgDKQmVXJvPrBkfbStojFXwoGyt4Z2gFXkWkhWWfnqOc1SgTbMS32Bj/Twy65XpteenmCC2SHQFjXcFgjGn7wLDEMAMe1UrWa2G9LsAyOZeJ3a8NmBs34aBbOR+JEhxuFBsHNDqNJV/6JU2ElUMRiVlv8amwymTxDYtphBqwjmLG3wy6KoFY1I/qG3LaUcraFx2ficU180hQX3L/vpas9p2lvOD4tuDFbb8vQHNxB08T7+BxxiVPTOdwXwC7U98FR+z1M9prsbY/MxY+eWGrKAWKOCFKCAJuFTUYSMdBw+gIxNe1+I/W2wb9jJ/6NvA4QDfSgsFv5hOY6UhuJm4Uk0CEGcUTXAPohMJeCXdoms="
